
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

url: http://techytushar.github.io/
baseurl: /
title: Tushar Mittal
author: Tushar Mittal
description: Personal blog and resume website.
avatar: profile.png
email: chiragmittal.mittal@gmail.com
github: techytushar # username
twitter: techy_tushar
linkedin: tusharmit
stackoverflow: users/5679285/tushar-mittal
google_analytics: UA-69391421-1

# for travis
exclude: [vendor]
