
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

url: http://techytushar.github.io
baseurl: /
title: Tushar Mittal (@techytushar)
author: Tushar Mittal
description: Tushar Mittal (techytushar) | GSoC'18 with SPDX | GCI Mentor with CloudCV | GitHub Campus Expert | Intel AI Student Ambassador | Data Science and Machine Learning enthusiast.
avatar: profile.jpeg
email: chiragmittal.mittal@gmail.com
github: techytushar
twitter: techy_tushar
linkedin: tusharmit
stackoverflow: users/5679285/tushar-mittal
codepen: techytushar
facebook: tusharmit
campus_expert: techytushar
kaggle: techytushar
disqus: techytushar
google_analytics: UA-110551930-1

# for travis
exclude: [vendor]
