
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

url: http://techytushar.github.io
baseurl: /
title: Tushar Mittal (@techytushar)
author: Tushar Mittal
description: Tushar Mittal's personal blog and portfolio website | Google Summer of Code 2018 Intern with SPDX | Github Campus Expert | Python developer and Machine Learning enthusiast from Kanpur.
avatar: profile.png
email: chiragmittal.mittal@gmail.com
github: techytushar
twitter: techy_tushar
linkedin: tusharmit
stackoverflow: users/5679285/tushar-mittal
codepen: techytushar
facebook: tusharmit
campus_expert: techytushar
disqus: techytushar
google_analytics: UA-110551930-1

# for travis
exclude: [vendor]
